### PR TITLE
Dirty data warning

### PR DESCRIPTION
**Pull request by shapiromatron**
half-baked; only use if helpful.

### CODE REVIEW

**Comment by bishwobhandari** [comment]
@shapiromatron  continued on the #110 branch. please review

**Comment by shapiromatron** [comment]
@bishwobhandari this was having issues when data was loaded from a clean page load - was this fixed?

**Comment by shapiromatron** [comment]
> @shapiromatron continued on the #110 branch. please review

Make

**Comment by shapiromatron** [comment]
Closed; successfully merged in #193

**Pull request closed without merging**
